title: Karleigh Moore
description: MIT 2017 | Computer Science and Comparative Media Studies

url: http://kar-moore.github.io/blog
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /about
 - title: Blog
   url: /blog.html
 - title: Contact
   url: /contact

social:
   github: kar-moore
   twitter: 
   facebook: 
   email: kjmoore@mit.edu

google_analytics: ""

linkedin_username: karleighmoore